version: '3.8'

services:
  app:
    build:
      context: .
      target: runner
    image: nacit-lilongwe:latest
    container_name: nacit-lilongwe
    restart: unless-stopped
    ports:
      - '3000:3000'
    env_file:
      - .env.docker
    environment:
      - NODE_ENV=production
      - PORT=3000
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  # Uncomment and configure this if you need a PostgreSQL database
  # postgres:
  #   image: postgres:15-alpine
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_USER: ${DB_USERNAME:-postgres}
  #     POSTGRES_PASSWORD: ${DB_PASSWORD:-admin}
  #     POSTGRES_DB: ${DB_DATABASE:-postgres}
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-postgres} -d ${DB_DATABASE:-postgres}"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

# Uncomment if using PostgreSQL
# volumes:
#   postgres_data:
